site_name: PyCafe plugin for MkDocs
site_url: https://mkdocs.py.cafe
docs_dir: "website"
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: 'highlight'
          validator: !!python/name:mkdocs_pycafe.validator
          format: !!python/object/apply:mkdocs_pycafe.formatter
            kwds:
              type: solara
              requirements: |
                altair
                anywidget
              link_text: |
                <img src="https://py.cafe/logos/pycafe_logo.png" style="height: 24px"> **Run and edit this code in Py.Cafe**
  - pymdownx.snippets:
      url_download: true