name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install flit
        run: pip install flit
      - name: Test optional dependencies
        run: flit install --deps=production --extras=flask,dev,examples,server # exclude assets, since that is not yet build
      - name: Uninstall
        run: pip uninstall solara -y
      - name: Build
        run: flit build
      - name: Install
        run: pip install dist/*.whl
      - name: Test import
        run: python -c "import solara"
      - name: Install hatch
        run: pip install hatch
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build assets
        run: (cd packages/assets; hatch build)
      - name: Publish solara-assets to PyPI
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.pypi_assets }}
        run: |
          (cd packages/assets; hatch publish)
      - name: remove assets
        run: rm -rf packages/assets/dist
      - name: Publish solara to PyPI
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          openssl sha256 dist/*
          flit publish
      - uses: actions/upload-artifact@v1
        with:
          name: distributions
          path: ./dist
